wsentinel:	
	gcc -c list_without_sentinel.c -o list_without_sentinel.o
	
	gcc main.c list_without_sentinel.o -o ./bin/main
	
	./bin/main

	
sentinel:
	gcc -c list_with_sentinel.c -o list_with_sentinel.o
	
	gcc main.c list_with_sentinel.o -o ./bin/main
	
	./bin/main

clean:
	rm *.o
	rm ./bin/main