contiguous:	
	gcc -c stack_contiguous.c -o stack_contiguous.o
	
	gcc main.c stack_contiguous.o -o ./bin/main
	
	./bin/main

	
linked:
	gcc -c stack_linked.c -o stack_linked.o
	
	gcc main.c stack_linked.o -o ./bin/main
	
	./bin/main

clean:
	rm *.o
	rm ./bin/main