contiguous:	
	gcc -c queue_contiguous.c -o queue_contiguous.o
	
	gcc main.c queue_contiguous.o -o ./bin/main
	
	./bin/main

	
linked:
	gcc -c queue_linked.c -o queue_linked.o
	
	gcc main.c queue_linked.o -o ./bin/main
	
	./bin/main

clean:
	rm *.o
	rm ./bin/main